//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTPTEmployee
    {
        public int EmployeeID { get; set; }
        public Nullable<int> HourlyPay { get; set; }
        public Nullable<int> HoursWorked { get; set; }
    
        public virtual TPTEmployee TPTEmployee { get; set; }
    }
}
