//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPTEmployee
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
    
        public virtual ContractTPTEmployee ContractTPTEmployee { get; set; }
        public virtual PermanentTPTEmployee PermanentTPTEmployee { get; set; }
    }
}
